%% Evaluates whether the current crop parameter value combination agrees
% with the constraints from the AquaCrop model that are supposed to guarantuee
% a physically sound crop phenology simulation:
function breakloop = AAOS_CheckPhenologyConstraints(Var,GDDcumsum)

PhenoConflictNames = string(fieldnames(Var));

for idx = 1:size(PhenoConflictNames,2)
    if isempty(find(GDDcumsum > Var.(PhenoConflictNames(idx)),1))
        PhenoConflictVals(idx) = 9999;
    else
        PhenoConflictVals(idx) = find(GDDcumsum > Var.(PhenoConflictNames(idx)),1);
    end
end

    PhenoConflicts =...
        [Var.Senescence < Var.Emergence + 1000,...
        Var.Senescence > Var.Emergence + 2000,...
        Var.Senescence < Var.MaxCanopy,...
        Var.Senescence > Var.Maturity,...
        Var.Maturity < Var.Emergence + 1500,...
        Var.Maturity > Var.Emergence + 2900,...
        Var.HIstart < Var.Emergence + 1000,...
        Var.HIstart > Var.Emergence + 1300,...
        (Var.Flowering >= Var.Senescence - Var.HIstart...
        + (Var.Maturity-Var.Senescence)/2),...
        (Var.HIstart + Var.Flowering) > Var.Maturity];

    breakloop = 0;
    if any(PhenoConflicts)
        disp(PhenoConflicts);
%         disp("Plot #"+Config.PlotIdxAll...
%             +" - Simulation #"+Config.SimRound...
%             +" - "+Config.TestVarName);
        disp("GDD of last available day = "+max(GDDcumsum))
        disp("Chosen phenology parameter values lead to one or more of the"...
        +"following conflicts (CD = 9999 = out of available weather input range):");
        
        disp("Senescence ("+Var.Senescence+" GDD)  <  Emergence + 1000 GDD ("+plus(Var.Emergence,1000)+" GDD)"...
            +"/ "+PhenoConflictVals(1)+" CD");
        disp("Senescence ("+Var.Senescence+" GDD)  >  Emergence + 2000 GDD ("+plus(Var.Emergence,2000)+" GDD)");
        disp("Senescence = "+Var.Senescence+" GDD/ "+PhenoConflictVals(2)+" CD < "...
            +Var.MaxCanopy+" GDD/ "+PhenoConflictVals(4)+" CD = MaxCanopy");
        disp("Senescence = "+Var.Senescence+" GDD/ "+PhenoConflictVals(2)+" CD > "...
            +Var.Maturity+" GDD/ "+PhenoConflictVals(3)+" CD = Maturity");
        disp("Maturity ("+Var.Maturity+" GDD)  <  Emergence + 1500 GDD ("+plus(Var.Emergence,1500)+" GDD)"...
            +"/ "+PhenoConflictVals(1)+" CD");
        disp("Maturity ("+Var.Maturity+" GDD)  >  Emergence + 2900 GDD ("+plus(Var.Emergence,2900)+" GDD)");
        disp("HIstart ("+Var.HIstart+" GDD)  <  Emergence + 1000 GDD ("+plus(Var.Emergence,1000)+" GDD)");
        disp("HIstart ("+Var.HIstart+" GDD)  >  Emergence + 1300 GDD ("+plus(Var.Emergence,1300)+" GDD)");
        disp("Flowering = "+Var.Flowering+" GDD/ "+PhenoConflictVals(7)+" CD >= "+...
            (Var.Senescence - Var.HIstart + (Var.Maturity-Var.Senescence)/2)+" GDD/ "+...
            (PhenoConflictVals(2)...
            - PhenoConflictVals(5)...
            + (PhenoConflictVals(3)...
            -PhenoConflictVals(2))/2)+...
            " CD = Senescence - HIstart + (Maturity - Senescence)/2");
        disp("FloweringEnd > Maturity = "+plus(Var.HIstart,Var.Flowering)+" GDD/"...
            +plus(PhenoConflictVals(5),PhenoConflictVals(7))+" CD > "...
            +Var.Maturity+" GDD/ "+PhenoConflictVals(3)+" = Maturity");
        breakloop = 1;
    end

