%% ONLY WORKS IF AOS OUTPUT UNIT = CD
%% Evaluates whether the current crop parameter value combination agrees
% with the constraints from the AquaCrop model that are supposed to guarantuee
% a physically sound crop phenology simulation:
function breakloop = AAOS_CheckPhenologyConstraints(Var,GDDcumsum,breakloop)

HarvestDay = size(GDDcumsum,1);

PhenoConflicts =...
    [Var.Senescence < Var.Emergence + 1000,...
    Var.Senescence > Var.Emergence + 2000,...
    Var.Senescence < Var.MaxCanopy,...
    Var.Senescence > Var.Maturity,...
    Var.Maturity <= Var.Canopy10Pct,...
    Var.Maturity < Var.Emergence + 1500,...
    Var.Maturity > Var.Emergence + 2900,...
    Var.Maturity <= Var.MaxCanopy,...
    Var.HIstart < Var.Emergence + 1000,...
    Var.HIstart > Var.Emergence + 1300,...
    (Var.HIstartCD + Var.YldFormCD) > HarvestDay,...
    (Var.Flowering >= Var.Senescence - Var.HIstart...
    + (Var.Maturity-Var.Senescence)/2),...
    (Var.HIstart + Var.Flowering) > Var.Maturity,...
    Var.Canopy10Pct == 0];

if any(PhenoConflicts)
    breakloop = 1;
end

