%% Evaluates whether the current crop parameter value combination agrees
% with the constraints from the AquaCrop model that are supposed to guarantuee
% a physically sound crop phenology simulation:
function breakloop = AAOS_CheckPhenologyConstraints(Config,Var,GDDcumsum,breakloop)

HarvestDay = size(GDDcumsum,1);
% Get user-defined conflict specifications
X = Config.PhenoConflicts;
X_1 = X(4:6);
X_1(X_1==-9999) = 9999;
X(4:6) = X_1;

% Check conflicts for given phenology values:
PhenoConflicts =...
    [Var.Senescence < Var.Emergence + X(1),...
    Var.Maturity < Var.Emergence + X(2),...
    Var.HIstart < Var.Emergence + X(3),...
    Var.Senescence > Var.Emergence + X(4),...
    Var.Maturity > Var.Emergence + X(5),...
    Var.HIstart > Var.Emergence + X(6),...
    Var.Senescence < Var.MaxCanopy,...
    Var.Senescence > Var.Maturity,...
    Var.Maturity <= Var.Canopy10Pct,...
    Var.Maturity <= Var.MaxCanopy,...
    (Var.HIstartCD + Var.YldFormCD) > HarvestDay,...
    (Var.Flowering >= Var.Senescence - Var.HIstart...
    + (Var.Maturity-Var.Senescence)/2),...
    (Var.HIstart + Var.Flowering) > Var.Maturity,...
    Var.Canopy10Pct == 0];
%disp(Var.Emergence + X(3));disp(Var.HIstart);disp(Var.Emergence + X(6));
% Determine if the given values produce any conflicts:
if any(PhenoConflicts)
    breakloop = 1;end


